# Generated by Django 4.0.1 on 2022-05-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=12)),
                ('price', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='')),
                ('unit', models.CharField(max_length=12)),
                ('stock', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[(1, '有货'), (2, '无货')], default=1)),
                ('des', models.CharField(max_length=200)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alc_name', models.CharField(max_length=12)),
                ('price', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='')),
                ('unit', models.CharField(max_length=12)),
                ('stock', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[(1, '有货'), (2, '无货')], default=1)),
                ('des', models.CharField(max_length=200)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
        ),
        migrations.CreateModel(
            name='AgricultureProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agr_name', models.CharField(max_length=12)),
                ('price', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='')),
                ('unit', models.CharField(max_length=12)),
                ('stock', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[(1, '有货'), (2, '无货')], default=1)),
                ('des', models.CharField(max_length=200)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
        ),
    ]
