# Generated by Django 4.0.1 on 2022-04-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(max_length=30)),
                ('travel_price', models.CharField(max_length=12)),
                ('travel_state', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='yunqiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yunqiu_name', models.CharField(max_length=32)),
                ('yunqiu_img', models.ImageField(upload_to='')),
                ('yunqiu_describe', models.CharField(max_length=128)),
                ('yuqiu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic_spot.travel')),
            ],
        ),
        migrations.CreateModel(
            name='rognzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rongzi_name', models.CharField(max_length=32)),
                ('rongzi_img', models.ImageField(upload_to='')),
                ('rongzi_describe', models.CharField(max_length=128)),
                ('rongzi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic_spot.travel')),
            ],
        ),
        migrations.CreateModel(
            name='fengling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fengling_name', models.CharField(max_length=32)),
                ('fengling_img', models.ImageField(upload_to='')),
                ('fengling_describe', models.CharField(max_length=128)),
                ('fengling_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic_spot.travel')),
            ],
        ),
        migrations.CreateModel(
            name='baishan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baishan_name', models.CharField(max_length=32)),
                ('baishan_img', models.ImageField(upload_to='')),
                ('baishan_describe', models.CharField(max_length=128)),
                ('baishan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic_spot.travel')),
            ],
        ),
    ]
