# Generated by Django 4.0.1 on 2022-05-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='shopping_id',
            new_name='shopping_name_name',
        ),
    ]
