# Generated by Django 4.0.1 on 2022-05-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_shopping_id_shopping_shopping_name_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='shopping_name_name',
            new_name='shopping_id',
        ),
    ]
