# Generated by Django 4.0.1 on 2022-04-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=12)),
                ('menu_type', models.CharField(max_length=12)),
                ('menu_price', models.CharField(max_length=12)),
                ('menu_img', models.ImageField(upload_to='')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritainment.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_type', models.CharField(max_length=12)),
                ('hostel_img', models.ImageField(upload_to='')),
                ('host_state', models.CharField(max_length=6)),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritainment.restaurant')),
            ],
        ),
    ]
